## **Homework 2**

### Create a copy of the notebook to start answering the questions. Name your notebook in the format HW1_lastname_firstname.ipynb to facilitate the grading process. 

### Answer all the questions, test your code to ensure there are no errors and the results are as expected. Once you have answered all the questions, save the final copy, then go to File-> click on Download.ipynb. Once the local copy has been downloaded, submit your file on Blackboard under the corresponding assignment section. Also provide us a link to your notebook during submission. 

### **The due date of this homework is 02/12/2021 (Friday).**

### Please ensure you follow all the steps mentioned in the homework.

### All the questions have a sample input and output to help you understand the question.

### You can submit your solutions any number of times until the deadline.


**Q1. Lets consider your data is like the below cell:**

**Q1-1**: Write a program that create a dataframe from the data.

**Q1-2:** Select people that are psychologist or teacher and their number of cars is greater than their family size.

**Q1-3:** Select people who have at most 2 family members and at least 1 car.

**Q1-4:** Write a code that get number of unique jobs in this dataset.





In [ ]:
data = {"name": ["Joseph", "Jacob", "Sam", "Jesee", "Ryan", "Lisa", "Lee"],
        "job": ["teacher", "psychologist", "data scientist", "software developer", "psychologist", "psychologist", "teacher"],
        "family_size": [3, 2, 1, 4, 2, 3, 2],
        "num_cars": [3, 1, 1, 2, 2, 4, 1]}

In [ ]:
# Type your solution here
# Q1-1
import pandas as pd
df = pd.DataFrame(data)
# Q1-2
print(df[((df.job == "psychologist") | (df.job == "teacher")) & (df.num_cars > df.family_size)])
# use | instead of "or", use & instead of "and" for dataframe
print()

# Q1-3
print(df[(df.family_size <= 2) & (df.num_cars >= 1)])
print()

# Q1-4:
print("There are", len(df['job'].unique()), "distinct jobs.")

   name           job  family_size  num_cars
5  Lisa  psychologist            3         4

    name             job  family_size  num_cars
1  Jacob    psychologist            2         1
2    Sam  data scientist            1         1
4   Ryan    psychologist            2         2
6    Lee         teacher            2         1

There are 4 distinct jobs.


**Q2. Lets consider you have two series like the below cell. Compute the mean of weights of each fruit.**

In [ ]:
import numpy as np
fruit = pd.Series(np.random.choice(['apple', 'banana', 'carrot'], 10))
weights = pd.Series(np.linspace(1, 10, 10))

In [ ]:
# Type your solution here
apple_list = []
banana_list = []
carrot_list = []
for i in range(0, len(fruit)):
  if fruit[i] == 'apple':
    apple_list.append(weights[i])
  elif fruit[i] == 'banana':
    banana_list.append(weights[i])
  elif fruit[i] == 'carrot':
    carrot_list.append(weights[i])
print("The mean of weights for apple is", round(np.mean(apple_list), 2))
print("The mean of weights for banana is", round(np.mean(banana_list), 2))
print("The mean of weights for carrot is", round(np.mean(carrot_list), 2))

The mean of weights for apple is 5.0
The mean of weights for banana is 6.5
The mean of weights for carrot is 5.4


**Q3. Consider the below course_name array:**

**Q3-1**: Write a NumPy program to get the indices of the sorted elements of **course_name** array.

**Q3-2:** Write numpy code to check whether each element of **course_name** array starts with "P".


In [ ]:
import numpy as np
course_name = np.array(['Python', 'JS', 'examples', 'PHP', 'html'])

In [ ]:
# Type your solution here
# Q3-1
print(np.argsort(course_name))
print()
# Q3-2
for item in course_name:
  if np.char.startswith(item.lower(), 'p'):
    print(item, "starts with \"P\"")
  else:
    print(item, "doesn't starts with \"P\"")

[1 3 0 2 4]

Python starts with "P"
JS doesn't starts with "P"
examples doesn't starts with "P"
PHP starts with "P"
html doesn't starts with "P"


**Q4. Consider the below student_id array:**

**Q4-1:** Reverse the **student_id** array. Print both original and reversed array.

**Q4-2:** Get the 3-largest values of **student_id** array.

In [ ]:
import numpy as np
student_id = np.array([1023, 5202, 6230, 1671, 1682, 5241, 4532])

In [ ]:
# Type your solution here
# Q4-1
print("Original array:", student_id)
print("Reversed array:", student_id[::-1])
print()

# Q4-2
print("Three largest values of the array: ")
print(np.sort(student_id)[-1])
print(np.sort(student_id)[-2])
print(np.sort(student_id)[-3])

Original array: [1023 5202 6230 1671 1682 5241 4532]
Reversed array: [4532 5241 1682 1671 6230 5202 1023]

Three largest values of the array: 
6230
5241
5202


# **Q5: Write a numpy program to print sum of all the multiples of 3 or 5 below 100**

In [ ]:
# Type your solution here

# Hint: you can use arange to start off
multiple3 = np.arange(3, 101, 3)
multiple5 = np.arange(5, 101, 5)
print("The sum of all the positive multiples of 3 or 5 below 100 is", np.sum(multiple3) + np.sum(multiple5))

The sum of all the positive multiples of 3 or 5 below 100 is 2733


**Q6. Consider the below array.**

Q6.1. Write a code to swap column 1 with column 2.

Q6.2. Write a code to swap row 0 with row 1.

In [ ]:
import numpy as np

arr = np.arange(12).reshape(3,4)
print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [ ]:
# Type your solution here
# Q6.1
print("Swap column 1 with column 2.")
arr[:,[1, 2]] = arr[:, [2, 1]]
print(arr)
print()
# Q6.2
print("Swap row 0 with row 1.")
arr[[0, 1]] = arr[[1, 0]]
print(arr)

Swap column 1 with column 2.
[[ 0  2  1  3]
 [ 4  6  5  7]
 [ 8 10  9 11]]

Swap row 0 with row 1.
[[ 4  6  5  7]
 [ 0  2  1  3]
 [ 8 10  9 11]]
